name: CIJava
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: |
        mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=libs/AnvilConverter.jar -DgroupId=net.minecraft.awzaw -DartifactId=anvil-converter -Dversion=1.0.0 -Dpackaging=jar -DgeneratePom=true
        mvn clean package
    - name: Copy artifacts
      run: |
        mkdir artifact
        cp target/*.jar artifact
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifact